project:
  type: website
  output-dir: docs

website:
  title: "LiChen Dong"
  favicon: ./images/avatar.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - research.qmd
      - clinical.qmd
      - teaching.qmd
      - dei.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

