---
title: "Mentoring and Teaching"
---

# Mentorship

## Mentorship Statement

### Overarching Philosophy
Effective mentorship benefit not only the mentee, but also the profession. A positive mentoring relationship fosters not only professional success of the mentee, but also their growth across many domains, including but not limited to confidence, initiative, perseverance, courage, and resilience. My mentorship aims to help students develop into young independent researchers who bring innovation and self-representation to the field. 


For a positive mentoring relationship, I abide to several principles. First, I provide **unconditional positive regard**, because growth does not take place without self-faith and belongingness, to which unconditional positive regard is the key. Next, I foster an **open and safe environment**, since problems cannot be solved and progress cannot be made if the expression of feelings or thoughts is withheld. Lastly, I ensure that my mentorship unbiasedly **serves the mentee**, **not the mentor**: the purpose of mentoring is to scaffold the development of an independent person, and not to benefit or extend myself. 


### Mentoring Goals
- Personalize mentorship to specific mentee.


- Emphasize the mentee's strengths not weaknesses.


- Guide the mentee in exploring academic interests.


- Establish the mentee’s confidence and self-efficacy.


- Foster the mentee’s research related skills.


- Help the mentee in developing independence. 

### Mentoring Approaches

### Self-evaluation

## Mentorship Experience

### Undergraduate

# Teaching

## Honors

- Psychology Department Teaching Award (Spring 2025)
- Psychology Department TA Award (Spring 2025)

## Teaching Statement


## Teaching Experience


### Courses Developed


### Teaching Assistantship

- PSYCH 610: Design and Analysis of Psychological Experiments (Spring 2025)
- PSYCH 710: General Linear Model (Fall 2024)
- PSYCH 710: Design and Analysis of Psychological Experiments (Spring 2024)
- PSYCH 610: Design and Analysis of Psychological Experiments (Fall 2023)

#### TA evaluation forms

<div>
```{=html}
<iframe width="100%" height="1000" src="./files/ta_eval_fall_2023.pdf"></iframe>
```
</div>

<div>
```{=html}
<iframe width="100%" height="1000" src="./files/ta_eval_spring_2024.pdf"></iframe>
```
</div>

<div>
```{=html}
<iframe width="100%" height="1000" src="./files/ta_eval_fall_2024.pdf"></iframe>
```
</div>

### Guest Lecturing

- Guest Lecture: PSYCH 807: Introduction to Conducting Psychotherapy. Intake Interview (February 2025)
- Guest Lecture: PSYCH 610: General Linear Model. Multiple Regression (October 2024)

#### Formal Feedback: Intake Interview

<div>
```{=html}
<iframe width="100%" height="1000" src="./files/guest_lecture_eval_intake_interview_02_13_2025.pdf"></iframe>
```
</div>
